// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjrbqhklcnrotbirqhxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcmJxaGtsY25yb3RiaXJxaHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzI0ODIsImV4cCI6MjA2ODQ0ODQ4Mn0.24RpJjnxqmXBDu2FgrAJbDtnld2yb0yrn3fwCznMCIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});